openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    <опис вашого додатку>
  # теги, що ви будете використовувати
# tags:
servers:
  - url: <http://localhost:3000>
  # - url: #посилання на задеплоєний сайт
# paths:
# тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
